apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-termination
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-termination
  template:
    metadata:
      labels:
        app: ssl-termination
    spec:
      containers:
        - name: app
          image: ufocultist/node-bulletin-board:latest
          ports:
          - containerPort: 8080
            name: app

        - name: httpd
          image: ufocultist/getting-started:latest
          ports:
          - containerPort: 80
            name: httpd
 
        - name: haproxy
          imagePullPolicy: IfNotPresent
          image: ssl-termination
          ports:
          - containerPort: 443
