apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-termination
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-termination
  template:
    metadata:
      labels:
        app: ssl-termination
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webapp1
          image: ufocultist/getting-started:latest
          ports:
          - containerPort: 3000
            name: webapp1
 
        - name: haproxy
          imagePullPolicy: Never
          image: ssl-termination
          ports:
          - containerPort: 443
